routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();


Auth::routes();




Route::get('/', 'PagesController@index');
Route::get('/about', 'PagesController@About');
Route::get('/services', 'PagesController@services');
Route::resource('posts','PostsController');
Auth::routes();

Route::get('/consultant/dashboard', 'ConsultantController@EditProfile')->name('consultant.dashboard');

Route::post('ajaxdata/postdata', 'AjaxdataController@postdata')->name('ajaxdata.postdata');

route::namespace('Admin')->prefix('admin')->middleware(['auth','auth.admin'])->name('admin.')->group(function(){
    route::resource('/users','UserController',['except'=>['show']]);
    route::get('/documents','UserController@document');
    route::get('/pending','UserController@pending');
    Route::put('/post/{id}/approve','UserController@approval')->name('post.approve');
    Route::delete('/post/{id}/approve','UserController@DestroyDocument')->name('post.destroydocument');
    route::post('/users/CreateMission_Consultant/{id}','UserController@CreateMission_Consultant');
    route::post('/users/CreateMission_Salarié/{id}','UserController@CreateMission_Salarié');
    route::get('/missions','UserController@mission');
    route::get('/users/{id}/missions','UserController@Affecter_Mission');
    route::delete('/Mission/{id}/destroy','UserController@DestroyMission')->name('users.destroyMission');

 
});
route::namespace('Consultant')->prefix('consultant')->middleware(['auth','auth.consultant'])->name('consultant.')->group(function(){
    route::resource('/dashboard','ConsultantController');

    route::get('/dashboard/{id}/Adresse_Famille_Edit','ConsultantController@Adresse_Famille_Edit');
    route::put('/dashboard/UpdateProfile/{id}','ConsultantController@UpdateProfile');
    route::get('/dashboard/{id}/Entreprise_Edit','ConsultantController@Entreprise_Edit');
    route::put('/dashboard/UpdateEntreprise/{id}','ConsultantController@UpdateEntreprise');
    route::get('/documents','ConsultantController@document')->name('documents');
    route::get('/missions','ConsultantController@mission')->name('missions');
    route::post('/Timesheet','ConsultantController@TimeSheet')->name('dashboard.TimeSheet');
    route::get('/Timesheet','ConsultantController@TimeSheet')->name('dashboard.TimeSheet');
  
    route::get('/Remplir','ConsultantController@Remplir')->name('remplir');
    Route::get('/export_excel/excel1', 'ConsultantController@export')->name('export_excel.excel');
    Route::get('/export_excel/excel', 'ConsultantController@export_view')->name('export_excel.excel.view');
    Route::get('/dynamic_pdf/pdf', 'ConsultantController@pdf');
    route::get('/cra','ConsultantController@cra')->name('cra');
    route::get('/tableau','ConsultantController@tableau')->name('tableau');
    route::post('/dashboard/CreateCra/{id}','ConsultantController@CreateCRA');
    route::get('/fiche','ConsultantController@fiche')->name('fiche');
    Route::get('/select/{id}/Month','ConsultantController@Select_Month');
      
});

route::namespace('Salarié')->prefix('salarié')->middleware(['auth','auth.salarié'])->name('salarié.')->group(function(){
    route::resource('/dashboard','SalarieController',['except'=>['show']]);
   
    route::get('/dashboard/{id}/Adresse_Famille_Edit','SalarieController@Adresse_Famille_Edit');
    route::put('/dashboard/UpdateProfile/{id}','SalarieController@UpdateProfile');
    route::get('/dashboard/{id}/Entreprise_Edit','SalarieController@Entreprise_Edit');
    route::put('/dashboard/UpdateEntreprise/{id}','SalarieController@UpdateEntreprise');
    route::get('/documents','SalarieController@document')->name('documents');
    route::get('/CRA','SalarieController@CRA')->name('cra');
    route::get('/missions','SalarieController@mission')->name('missions');
    route::get('/fiche','SalarieController@fiche')->name('fiche');
    route::post('/dashboard/CreateCra/{id}','SalarieController@CreateCRA');
    Route::get('/select/{id}/month','SalarieController@Select_Month');
  
});
// Create file upload form
Route::get('/upload-file', 'DocumentUpload@createForm');

// Store file
Route::post('/upload-file', 'DocumentUpload@fileUpload')->name('fileUpload');

app/User.php
<?php

namespace App;
use Auth;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPassword as ResetPasswordNotification;
use Illuminate\Database\Eloquent\Model;
use App\documents;
use App\missions;
Use DB;
class User extends Authenticatable 
{
    use Notifiable;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users_rh';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','type_users','CIN','numéro_CNSS','Adresse','téléphone','situation_familiale','Date_entrée','nbr_enfant','Materiel_Pc','Materiel_Voiture','Materiel_Télé'
    ];
       

   
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

 
public function isRole(){
    return $this->type_users;
}
public function sendPasswordResetNotification($token)
    {
        // Your your own implementation.
        $this->notify(new ResetPasswordNotification($token));
    }
    public function documents(){
        return $this->belongsToMany('App\documents','documents_user_rh');  
    }
    public function missions(){
        return $this->belongsToMany('App\missions','missions_user_rh');  
    }
    public function Cra(){
        return $this->belongsToMany('App\Cra');  
    }
    public static function Consultant_Salarié(){
      
        $documents= DB::table('users_rh')->whereIn( 'type_users',  ['salarié','consultant'])->get();
          
        return $documents;
    }
    public static function Mission_id($id)
    {
        $data= DB::table('missions_user_rh')
            ->where('user_id',$id)
            ->value('missions_id');
        
         if ($data==null){return 1;}
         else
            return  $data;
       
    }
    public static function Mission($id)
    {
        $data= DB::table('missions_rh')
        ->join('missions_user_rh','missions_user_rh.missions_id','=','missions_rh.id')
        ->where('user_id',$id)
        ->first();
       
    return $data;
       
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\type_users;
use App\missions;
use App\documents;
use \Illuminate\Notifications\Notifiable;
use App\Notifications\AuthorPostApproved;
use App\Notifications\NewPostNotify;
use Illuminate\Support\Facades\Notification;
use Illuminate\support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use DB;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        return view('admin.users.index')->with('users',User::all());
    }
    public function mission()
    {   
        return view('admin.users.Affecter_Mission')->with('users',User:: Consultant_Salarié());
    }
    public function document()
    {   
        return view('admin.users.document')->with('type_users',type_users::all())->with('documents',documents::all());
    }
    public function pending()
    {   
        return view('admin.users.pending')->with('type_users',type_users::all())->with('documents',documents::all());
    }
    public function Affecter_Mission($id)
    {   $user=User::find($id);
        if( $user->type_users=="consultant")
        {
        return view('admin.users.Missions_Consultant')->with('user',$user);
        }
        else 
        if( $user->type_users=="salarié")
        {
        return view('admin.users.Mission_salarié')->with('user',$user);
        }
    }
   
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' =>'required',
            'email' =>'required|unique:users_rh',
            'password' =>'required',
            'type_users' =>'required',

        ]);
       $user =new User;
       $user->type_users=$request->input('type_users');
       $user->name=$request->input('name');
       $user->email=$request->input('email');
   
       $user->password = bcrypt($request->input('password'));
  
       $user->save();
        return redirect()->route('admin.users.index');
    }
    public function CreateMission_Salarié(Request $request,$id)
    {
        //
        $request->validate([
            'Client' =>'required',
            'Responsable' =>'required',
            'Intitulé_Mission' =>'required',
           


        ]);
       $user =new Missions;
       $user->Client=$request->input('Client');
       $user->Responsable=$request->input('Responsable');
       
       $user->Intitulé_Mission=$request->input('Intitulé_Mission');
        
       $user->save();
       $user->Users()->sync($request->Users);
      
       $users = User::find($id);
      
      
       $users->is_affected=true;
       $users->save();
        return redirect()->route('admin.users.index');
    }
    public function CreateMission_Consultant(Request $request,$id)
    {
        //
        $request->validate([
            'Client' =>'required',
            'Responsable' =>'required',
            'Intitulé_Mission' =>'required',
            'Date_Debut' =>'required',
            'numéro_Bncmd_encours' =>'required',
            'Date_Fin' =>'required',
         


        ]);
       $user =new Missions;
       $user->Client=$request->input('Client');
       $user->Responsable=$request->input('Responsable');
       $user->Date_Debut=$request->input('Date_Debut');
       $user->Intitulé_Mission=$request->input('Intitulé_Mission');
       $user->numéro_Bncmd_encours=$request->input('numéro_Bncmd_encours');
       $user->Date_Fin=$request->input('Date_Fin');
       $user->save();
       $user->Users()->sync($request->Users);
      
       $users = User::find($id);
      
       $users->is_affected=true;
       $users->save();
        
     
        return redirect()->route('admin.users.index');
    }
    public function setPasswordAttribute($value){
        $this->attributes['password'] = bcrypt($value);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->id ==$id)
        {
            return redirect()->route('admin.users.index');
            
        }
        return view('admin.users.edit')->with(['user'=>User::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->id ==$id)
        {
            return redirect()->route('admin.users.index');
            
        }
        $request->validate([
            'name' =>'required',
            'type_users' =>'required',
            'email' =>'required',


        ]);
        $user = User::find($id);
        $user->type_users=$request->input('type_users');
        $user->name=$request->input('name');
        $user->email=$request->input('email');
   
        $user->save();
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
      
    
        $doc= DB::table('documents_rh')
        ->join('documents_user_rh','documents_user_rh.documents_id','=','documents_rh.id')
        ->where('user_id',$id)
        ->delete();
        
       $user->documents()->detach();
       $user->delete();
        return redirect()->route('admin.users.index');
    }
    public function destroyDocument($id)
    {
        $document = documents::find($id);
        $document->delete();
        return redirect()->back();
    }
    public function destroyMission($id)
    {
        $mission = Missions::find($id);
        $user=User::find($mission->users()->first()->id);
       $user->is_affected=false;
       $user->save();
        $mission->users()->detach();
       
        $mission->delete();

        return redirect()->back();
    }
    public function approval($id)
    {
        $post = Documents::find($id);
        if ($post->is_approved == false)
        {
            $post->is_approved = true;
            $post->save();
            /** 
            $post->users->first()->notify(new AuthorPostApproved($post));
            $subscribers = User::all();
            foreach ($subscribers as $subscriber)
            {
                Notification::route('mail',$subscriber->email)
                    ->notify(new NewPostNotify($post));
            }
            **/

            Toastr::success('Post Successfully Approved :)','Success');
        } else {
            Toastr::info('This Post is already approved','Info');
        }
        return redirect()->back();
    }
 
}

resources/views/admin/users/Document.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container-fluid">
  <div class="row">
   
    <nav class="col-sm-18  bg-light sidebar">
      <div class="p-4 mb-1 bg-dark text-white col-sm-14 " >Espace Admin</div>
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          
          <li class="nav-item">
            <a class="nav-link active" href="/">
             
              <span data-feather="home"></span>
              Dashboard <i class="fa fa-tachometer fa-lg" aria-hidden="true"></i><span class="sr-only">(current)</span> 
              
            </a>
            
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="missions">
              <span data-feather="shopping-cart"></span>
              Missions <i class="fa fa-briefcase fa-lg" aria-hidden="true"></i></i> 
            </a>
          </li>
        <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Documents <i class="fa fa-file-text-o fa-lg" aria-hidden="true"></i>
    </a>
    <div class="dropdown-menu bg-light sidebar" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="documents"> Documents </a>
      
   
      <a class="dropdown-item" href="pending">Gestion des Documents</a>
    
  </li>
       
         
          <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}"
          onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
           {{ __('Logout') }}
           <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
       </a>
       <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
      
    </form>
 
       <li >
        </ul>

        
      </div>
    </nav>

      
    
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Gestion des Documents</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <h1 class="h5">Bonjour   
              {{ Auth::user()->name }} <span class="caret"></span>
          </a></h1>
          </div>
         
        </div>
      </div>

<div class="container mt-5">
  <form action="{{route('fileUpload')}}" method="post" enctype="multipart/form-data">
    @csrf
      @if ($message = Session::get('success'))
      <div class="alert alert-success">
          <strong>{{ $message }}</strong>
      </div>
    @endif

    @if (count($errors) > 0)
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
    @endif
    <table class="table table-striped">
      <thead>
        <tr class="table-primary">
          <th> Partager Un Document </i></th>
          <th></th>
          <th>
          
           
          </th>
        </tr>
      </thead>
      <tbody>
       
      
           
        <tr>
          <td>Choisir un fichier</td>
          <td><div class="custom-file">
            <input type="file" name="file" class="custom-file-input" id="chooseFile" required>
            <label class="custom-file-label" for="chooseFile">Select file</label>
        </div>
                          
      
          <td> </td>
           
        </tr>
        <tr class="bg-warning">
            <td  >Fichier destiné à:</td>
            <td></td>
           <td></td>
          </tr>
          @foreach($type_users as $type_user)
          
      
        <tr>
        
            <td> <label>{{$type_user->name}}</label></td>
            <td >  <div class="form-check">
              
              <input type="checkbox" name="type_users[]"  value="{{$type_user->id}}" ></td>
              <input type="hidden" name="Users[]" value="{{Auth::user()->id}}"></td>
            <td></td>
            
          </tr>
          @endforeach
        <tr>
   
          <td></td>
          <td><button type="submit" name="submit" class="btn btn-primary ">
            Upload Files
        </button>
      
    </td>
         <td></td>
        </tr>
      </tbody>
      </table>
        </form>
   
        @foreach ($documents as $documents)

        <div class="document danger">
            <div class="document-body">
                <a href="{{url('/')}}/{{ Storage::disk('local')->url('uploads/' .$documents ->name  )}}"><i class="fa fa-file" aria-hidden="true"></i></a>
            </div>
            <div class="document-footer">
                <span class="document-name"> {{$documents ->name}}</span>
                <span class="document-description"> {{$documents ->file_size}} Ko </span>
            </div>
        </div>
        @endforeach
    </main>
    </div>
      </div>
  
      
 

      
      
      
        

      
  
<

  
      
     
  
  @endsection

resources/views/admin/users/pending.blade.php
@extends('layouts.app')
 <!-- JQuery DataTable Css -->
 <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">



@section('content')

    
    
<div class="container-fluid">
    <div class="row">
     
      <nav class="col-sm-18  bg-light sidebar">
        <div class="p-4 mb-1 bg-dark text-white col-sm-14 " >Espace Admin</div>
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            
            <li class="nav-item">
              <a class="nav-link active" href="/">
               
                <span data-feather="home"></span>
                Dashboard <i class="fa fa-tachometer fa-lg" aria-hidden="true"></i><span class="sr-only">(current)</span> 
                
              </a>
              
            </li>
           
            <li class="nav-item">
              <a class="nav-link" href="missions">
                <span data-feather="shopping-cart"></span>
                Missions <i class="fa fa-briefcase fa-lg" aria-hidden="true"></i></i> 
              </a>
            </li>
          <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Documents <i class="fa fa-file-text-o fa-lg" aria-hidden="true"></i>
      </a>
      <div class="dropdown-menu bg-light sidebar" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="documents"> Documents </a>
        
     
        <a class="dropdown-item" href="pending">Gestion des Documents</a>
      
    </li>
         
           
            <li class="nav-item">
            <a class="nav-link" href="{{ route('logout') }}"
            onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
             {{ __('Logout') }}
             <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
         </a>
         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
        
      </form>
   
         <li >
          </ul>
  
          
        </div>
      </nav>
  
    
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Gestion des Utilisateurs</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <h1 class="h5">Bonjour   
              {{ Auth::user()->name }} <span class="caret"></span>
          </a></h1>
          </div>
         
        </div>
      </div>
   
    <div class="container-fluid">
    
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-lg-12 col-lg-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Tous le documents
                            <span class="badge bg-blue">{{ $documents->count() }}</span>
                        </h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nom</th>
                                   
                                
                                    <th>Approbation</th>
                                    <th>Auteur</th>
                                    <th>Type Auteur</th>
                                    
                                   
                                    <th>Created At</th>
                                    {{--<th>Updated At</th>--}}
                                    <th>Action</th>
                                </tr>
                                </thead>
                              
                                <tbody>
                                    @foreach($documents as $post)
                                        <tr>
                                            <td>{{ $post->id }}</td>
                                           
                                            <td><a href="{{url('/')}}/{{ Storage::disk('local')->url('uploads/' .$post->name  )}}">{{ $post->name }}</a> </td>
                                          
                                            <td>
                                                @if($post->is_approved == true)
                                                    <span class="badge bg-blue">Approuvé</span>
                                                @else
                                                    <span class="badge bg-pink">En attente</span>
                                                @endif
                                            </td>
                                            <td>{{ $post->users()->first()->name }}</td>
                                            <td>{{  $post->users()->first()->type_users }}</td>
                                            <td>{{ $post->created_at }}</td>
                                            {{--<td>{{ $post->updated_at }}</td>--}}
                                            <td >
                                                @if($post->is_approved == false)
                                                    <button type="button" class="btn btn-success waves-effect" onclick="approvePost({{ $post->id }})">
                                                        <i class="material-icons">Approuver </i>
                                                    
                                                        
                                                    </button>
                                                    <hr>
                                                    <form method="post" action="{{ route('admin.post.approve',$post->id) }}" id="approval-form-{{ $post->id }}" style="display: none">
                                                        @csrf
                                                        @method('PUT')
                                                        
                                                    </form>
            
                                                @endif
                                               
                                                       <form action="{{route('admin.post.destroydocument',$post->id)}}" method="POST">
                                                   
                                                   
                                                      
                                                            @csrf
                                                          {{method_field('DELETE')}}
                                                             <button type="submit" class="btn btn-danger">Supprimer</button>
                                                        </form>
                                               
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
</div>
</div>

@endsection


    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
    <script type="text/javascript">
        function deletePost(id) {
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
        function approvePost(id) {
            swal({
                title: 'Are you sure?',
                text: "You went to approve this post ",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Oui, Approuver!',
                cancelButtonText: 'No, Annuler!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('approval-form-'+ id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'The post remain pending :)',
                        'info'
                    )
                }
            })
        }
    </script>