routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();


Auth::routes();




Route::get('/', 'PagesController@index');
Route::get('/about', 'PagesController@About');
Route::get('/services', 'PagesController@services');
Route::resource('posts','PostsController');
Auth::routes();

Route::get('/consultant/dashboard', 'ConsultantController@EditProfile')->name('consultant.dashboard');

Route::post('ajaxdata/postdata', 'AjaxdataController@postdata')->name('ajaxdata.postdata');

route::namespace('Admin')->prefix('admin')->middleware(['auth','auth.admin'])->name('admin.')->group(function(){
    route::resource('/users','UserController',['except'=>['show']]);
    route::get('/documents','UserController@document');
    route::get('/pending','UserController@pending');
    Route::put('/post/{id}/approve','UserController@approval')->name('post.approve');
    Route::delete('/post/{id}/approve','UserController@DestroyDocument')->name('post.destroydocument');
    route::post('/users/CreateMission_Consultant/{id}','UserController@CreateMission_Consultant');
    route::post('/users/CreateMission_Salarié/{id}','UserController@CreateMission_Salarié');
    route::get('/missions','UserController@mission');
    route::get('/users/{id}/missions','UserController@Affecter_Mission');
    route::delete('/Mission/{id}/destroy','UserController@DestroyMission')->name('users.destroyMission');

 
});
route::namespace('Consultant')->prefix('consultant')->middleware(['auth','auth.consultant'])->name('consultant.')->group(function(){
    route::resource('/dashboard','ConsultantController');

    route::get('/dashboard/{id}/Adresse_Famille_Edit','ConsultantController@Adresse_Famille_Edit');
    route::put('/dashboard/UpdateProfile/{id}','ConsultantController@UpdateProfile');
    route::get('/dashboard/{id}/Entreprise_Edit','ConsultantController@Entreprise_Edit');
    route::put('/dashboard/UpdateEntreprise/{id}','ConsultantController@UpdateEntreprise');
    route::get('/documents','ConsultantController@document')->name('documents');
    route::get('/missions','ConsultantController@mission')->name('missions');
    route::post('/Timesheet','ConsultantController@TimeSheet')->name('dashboard.TimeSheet');
    route::get('/Timesheet','ConsultantController@TimeSheet')->name('dashboard.TimeSheet');
  
    route::get('/Remplir','ConsultantController@Remplir')->name('remplir');
    Route::get('/export_excel/excel1', 'ConsultantController@export')->name('export_excel.excel');
    Route::get('/export_excel/excel', 'ConsultantController@export_view')->name('export_excel.excel.view');
    Route::get('/dynamic_pdf/pdf', 'ConsultantController@pdf');
    route::get('/cra','ConsultantController@cra')->name('cra');
    route::get('/tableau','ConsultantController@tableau')->name('tableau');
    route::post('/dashboard/CreateCra/{id}','ConsultantController@CreateCRA');
    route::get('/fiche','ConsultantController@fiche')->name('fiche');
    Route::get('/select/{id}/Month','ConsultantController@Select_Month');
      
});

route::namespace('Salarié')->prefix('salarié')->middleware(['auth','auth.salarié'])->name('salarié.')->group(function(){
    route::resource('/dashboard','SalarieController',['except'=>['show']]);
   
    route::get('/dashboard/{id}/Adresse_Famille_Edit','SalarieController@Adresse_Famille_Edit');
    route::put('/dashboard/UpdateProfile/{id}','SalarieController@UpdateProfile');
    route::get('/dashboard/{id}/Entreprise_Edit','SalarieController@Entreprise_Edit');
    route::put('/dashboard/UpdateEntreprise/{id}','SalarieController@UpdateEntreprise');
    route::get('/documents','SalarieController@document')->name('documents');
    route::get('/CRA','SalarieController@CRA')->name('cra');
    route::get('/missions','SalarieController@mission')->name('missions');
    route::get('/fiche','SalarieController@fiche')->name('fiche');
    route::post('/dashboard/CreateCra/{id}','SalarieController@CreateCRA');
    Route::get('/select/{id}/month','SalarieController@Select_Month');
  
});
// Create file upload form
Route::get('/upload-file', 'DocumentUpload@createForm');

// Store file
Route::post('/upload-file', 'DocumentUpload@fileUpload')->name('fileUpload');

app/User.php
<?php

namespace App;
use Auth;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPassword as ResetPasswordNotification;
use Illuminate\Database\Eloquent\Model;
use App\documents;
use App\missions;
Use DB;
class User extends Authenticatable 
{
    use Notifiable;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users_rh';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','type_users','CIN','numéro_CNSS','Adresse','téléphone','situation_familiale','Date_entrée','nbr_enfant','Materiel_Pc','Materiel_Voiture','Materiel_Télé'
    ];
       

   
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

 
public function isRole(){
    return $this->type_users;
}
public function sendPasswordResetNotification($token)
    {
        // Your your own implementation.
        $this->notify(new ResetPasswordNotification($token));
    }
    public function documents(){
        return $this->belongsToMany('App\documents','documents_user_rh');  
    }
    public function missions(){
        return $this->belongsToMany('App\missions','missions_user_rh');  
    }
    public function Cra(){
        return $this->belongsToMany('App\Cra');  
    }
    public static function Consultant_Salarié(){
      
        $documents= DB::table('users_rh')->whereIn( 'type_users',  ['salarié','consultant'])->get();
          
        return $documents;
    }
    public static function Mission_id($id)
    {
        $data= DB::table('missions_user_rh')
            ->where('user_id',$id)
            ->value('missions_id');
        
         if ($data==null){return 1;}
         else
            return  $data;
       
    }
    public static function Mission($id)
    {
        $data= DB::table('missions_rh')
        ->join('missions_user_rh','missions_user_rh.missions_id','=','missions_rh.id')
        ->where('user_id',$id)
        ->first();
       
    return $data;
       
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\type_users;
use App\missions;
use App\documents;
use \Illuminate\Notifications\Notifiable;
use App\Notifications\AuthorPostApproved;
use App\Notifications\NewPostNotify;
use Illuminate\Support\Facades\Notification;
use Illuminate\support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use DB;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        return view('admin.users.index')->with('users',User::all());
    }
    public function mission()
    {   
        return view('admin.users.Affecter_Mission')->with('users',User:: Consultant_Salarié());
    }
    public function document()
    {   
        return view('admin.users.document')->with('type_users',type_users::all())->with('documents',documents::all());
    }
    public function pending()
    {   
        return view('admin.users.pending')->with('type_users',type_users::all())->with('documents',documents::all());
    }
    public function Affecter_Mission($id)
    {   $user=User::find($id);
        if( $user->type_users=="consultant")
        {
        return view('admin.users.Missions_Consultant')->with('user',$user);
        }
        else 
        if( $user->type_users=="salarié")
        {
        return view('admin.users.Mission_salarié')->with('user',$user);
        }
    }
   
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' =>'required',
            'email' =>'required|unique:users_rh',
            'password' =>'required',
            'type_users' =>'required',

        ]);
       $user =new User;
       $user->type_users=$request->input('type_users');
       $user->name=$request->input('name');
       $user->email=$request->input('email');
   
       $user->password = bcrypt($request->input('password'));
  
       $user->save();
        return redirect()->route('admin.users.index');
    }
    public function CreateMission_Salarié(Request $request,$id)
    {
        //
        $request->validate([
            'Client' =>'required',
            'Responsable' =>'required',
            'Intitulé_Mission' =>'required',
           


        ]);
       $user =new Missions;
       $user->Client=$request->input('Client');
       $user->Responsable=$request->input('Responsable');
       
       $user->Intitulé_Mission=$request->input('Intitulé_Mission');
        
       $user->save();
       $user->Users()->sync($request->Users);
      
       $users = User::find($id);
      
      
       $users->is_affected=true;
       $users->save();
        return redirect()->route('admin.users.index');
    }
    public function CreateMission_Consultant(Request $request,$id)
    {
        //
        $request->validate([
            'Client' =>'required',
            'Responsable' =>'required',
            'Intitulé_Mission' =>'required',
            'Date_Debut' =>'required',
            'numéro_Bncmd_encours' =>'required',
            'Date_Fin' =>'required',
         


        ]);
       $user =new Missions;
       $user->Client=$request->input('Client');
       $user->Responsable=$request->input('Responsable');
       $user->Date_Debut=$request->input('Date_Debut');
       $user->Intitulé_Mission=$request->input('Intitulé_Mission');
       $user->numéro_Bncmd_encours=$request->input('numéro_Bncmd_encours');
       $user->Date_Fin=$request->input('Date_Fin');
       $user->save();
       $user->Users()->sync($request->Users);
      
       $users = User::find($id);
      
       $users->is_affected=true;
       $users->save();
        
     
        return redirect()->route('admin.users.index');
    }
    public function setPasswordAttribute($value){
        $this->attributes['password'] = bcrypt($value);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->id ==$id)
        {
            return redirect()->route('admin.users.index');
            
        }
        return view('admin.users.edit')->with(['user'=>User::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->id ==$id)
        {
            return redirect()->route('admin.users.index');
            
        }
        $request->validate([
            'name' =>'required',
            'type_users' =>'required',
            'email' =>'required',


        ]);
        $user = User::find($id);
        $user->type_users=$request->input('type_users');
        $user->name=$request->input('name');
        $user->email=$request->input('email');
   
        $user->save();
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
      
    
        $doc= DB::table('documents_rh')
        ->join('documents_user_rh','documents_user_rh.documents_id','=','documents_rh.id')
        ->where('user_id',$id)
        ->delete();
        
       $user->documents()->detach();
       $user->delete();
        return redirect()->route('admin.users.index');
    }
    public function destroyDocument($id)
    {
        $document = documents::find($id);
        $document->delete();
        return redirect()->back();
    }
    public function destroyMission($id)
    {
        $mission = Missions::find($id);
        $user=User::find($mission->users()->first()->id);
       $user->is_affected=false;
       $user->save();
        $mission->users()->detach();
       
        $mission->delete();

        return redirect()->back();
    }
    public function approval($id)
    {
        $post = Documents::find($id);
        if ($post->is_approved == false)
        {
            $post->is_approved = true;
            $post->save();
            /** 
            $post->users->first()->notify(new AuthorPostApproved($post));
            $subscribers = User::all();
            foreach ($subscribers as $subscriber)
            {
                Notification::route('mail',$subscriber->email)
                    ->notify(new NewPostNotify($post));
            }
            **/

            Toastr::success('Post Successfully Approved :)','Success');
        } else {
            Toastr::info('This Post is already approved','Info');
        }
        return redirect()->back();
    }
 
}

resources/views/salarié/users/Adresse_Famille.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="row">
   
    <nav class="col-sm-18  bg-light sidebar">
      <div class="p-4 mb-1 bg-dark text-white col-sm-14 " >Espace Salarié</div>
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          
          <li class="nav-item">
            <a class="nav-link active"  href="{{ route('salarié.dashboard.index') }}">
             
              <span data-feather="home"></span>
              Dashboard <i class="fa fa-tachometer fa-lg" aria-hidden="true"></i><span class="sr-only">(current)</span> 
              
            </a>
            
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.fiche') }}">
              <span data-feather="file"></span>
              Fiche Identification <i class="fa fa-fw fa-user fa-lg"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.missions') }}">
              <span data-feather="shopping-cart"></span>
              Missions <i class="fa fa-briefcase fa-lg" aria-hidden="true"></i></i> 
            </a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.documents') }}">
              <span data-feather="shopping-cart"></span>
           Documents<i class="fa fa-file-text-o fa-lg" aria-hidden="true"></i>
            </a>
          </li>
       <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.cra') }}">
              <span data-feather="shopping-cart"></span>
           Cra<i class="fa fa-clock-o  fa-lg" aria-hidden="true"></i>
            </a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              NDF<i class="fal fa-quidditch"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Salaires <i class="fa fa-usd fa-lg" aria-hidden="true"></i>
            </a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}"
          onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
           {{ __('Logout') }}
           <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
       </a>
       <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
      
    </form>
 
       <li >
        </ul>

        
      </div>
    </nav>
  

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Mes Informations</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <h1 class="h5">Bonjour   
          {{ Auth::user()->name }} <span class="caret"></span>
      </a></h1>
      </div>
     
    </div>
  </div>
  <div class="container">

    
           
               
                    <form action="{{url('salarié/dashboard/UpdateProfile',Auth::user()->id)}}" method="POST">
                      @csrf
                       {{method_field('PUT')}}
              
                   
                       
                        
                     
                      
                
                   
                        
                        
                      
                   
                   
                     
                      
                      
                   
                  
                    
              
         


  
<table class="table table-striped">
  <thead>
    <tr class="table-primary">
      <th> Adresse et Situation familiale <i class="fa fa-home fa-lg" aria-hidden="true"></i></th>
      <th></th>
      <th>
    
       
      </th>
    </tr>
  </thead>
  <tbody>
   
    <tr>
      <td>Situation familiale</td>
      <td >  <select class="form-control" name="situation_familiale">
        @foreach(["Célibataire" => "Célibataire", "divorcé(e)" => "divorcé(e)","marié(é)"=> "marié(é)","Veuf(ve)"=> "Veuf(ve)"] AS $situation_familiale => $contactLabel)    
        <option value="{{ $situation_familiale }}" {{ old("type_users",Auth::user()->situation_familiale) == $situation_familiale ? "selected" : "" }}>{{ $contactLabel }}</option>
        @endforeach
    </select></td>
      <td></td>
      
    </tr>
       
    <tr>
      <td>Nombre D'enfants</td>
      <td><input type="text" class="form-control" name="nbr_enfant"  placeholder="Votre Email" value="{{ Auth::user()->nbr_enfant }}" required autocomplete="nbr_enfant" autofocus>
                      
       
      <td> </td>
       
    </tr>
    <tr>
      <td>Adresse</td>
      <td><input type="text" class="form-control" name="Adresse"  placeholder="Votre Adresse" value="{{ Auth::user()->Adresse }}" required autocomplete="Adresse" autofocus></td>
     <td></td>
    </tr>
    
    <tr>
      <td></td>
      <td><button type="submit" class="btn btn-primary btn-lg">
        Update
    </button>
</td>
     <td></td>
    </tr>
    </form>
</main>
</div>
  </div>
</div>
</div>
  
    </div>
@endsection
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    

resources/views/salarié/users/CRA.blade.php
@extends('layouts.graphe')

@section('content')
<div class="container-fluid">
  <div class="row">
   
    <nav class="col-sm-18  bg-light sidebar">
      <div class="p-4 mb-1 bg-dark text-white col-sm-14 " >Espace Salarié</div>
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          
          <li class="nav-item">
            <a class="nav-link active"  href="{{ route('salarié.dashboard.index') }}">
             
              <span data-feather="home"></span>
              Dashboard <i class="fa fa-tachometer fa-lg" aria-hidden="true"></i><span class="sr-only">(current)</span> 
              
            </a>
            
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.fiche') }}">
              <span data-feather="file"></span>
              Fiche Identification <i class="fa fa-fw fa-user fa-lg"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.missions') }}">
              <span data-feather="shopping-cart"></span>
              Missions <i class="fa fa-briefcase fa-lg" aria-hidden="true"></i></i> 
            </a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.documents') }}">
              <span data-feather="shopping-cart"></span>
           Documents<i class="fa fa-file-text-o fa-lg" aria-hidden="true"></i>
            </a>
          </li>
       <li class="nav-item">
            <a class="nav-link" href="{{ route('salarié.cra') }}">
              <span data-feather="shopping-cart"></span>
           Cra<i class="fa fa-clock-o  fa-lg" aria-hidden="true"></i>
            </a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              NDF<i class="fal fa-quidditch"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Salaires <i class="fa fa-usd fa-lg" aria-hidden="true"></i>
            </a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}"
          onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
           {{ __('Logout') }}
           <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
       </a>
       <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
      
    </form>
 
       <li >
        </ul>

        
      </div>
    </nav>

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
  
  <img src="{{ asset('img/white.png') }}" class="white" >
 
  <table class="table table-striped">
    <thead>
      <tr class="table-primary">
        <th> Ajouter Une Operation</i></th>
        <th></th>
        <th>
      
         
        </th>
      </tr>
    </thead>
    <tbody>
      <form action="{{url('salarié/dashboard/CreateCra',Auth::user()->id)}}" method="POST">
        @csrf
         
      <tr>
        <td>Ligne De Crédit</td>
        <td >  <select class="form-control" name="Ligne_de_Crédit">
          @foreach(["Congé payé " => "Congé payé", "Congé sans solde " => "Congé sans solde ","Frais généraux" => "Frais généraux ","Jours fériés"=> "Jours fériés"] AS $Ligne_Credit => $contactLabel)    
          <option value="{{$Ligne_Credit }}" >{{ $contactLabel }}</option>
          @endforeach
      </select></td>
        <td></td>
        
      </tr>
      
      <tr>
        <td>Projet</td>
        <td><input type="text" class="form-control" name="Projet"  placeholder="Projet"  required autocomplete="Projet" autofocus></td>
       <td></td>
      </tr>
      <tr>
        <td>Date</td>
        <td><input type="date" class="form-control" name="Date"  placeholder="Date "  required autocomplete="Date" autofocus></td>
       <td></td>
      </tr>
      <tr>
        <td>Nombre D'heures</td>
        <td><input type="text" class="form-control" name="nbr_heures"  placeholder="Nombre D'heures"  required autocomplete="nbr_heures" autofocus>
                        
         
        <td> <input type="hidden" name="Users[]" value="{{Auth::user()->id}}"> </td>
         
      </tr>
      <tr>
        <td>Commentaire</td>
        <td> 
          <textarea class="form-control" name="Commentaire" rows="3"></textarea></td>
       <td></td>
      </tr>
      
      <tr>
        <td></td>
        <td><button type="submit" class="btn btn-primary btn-lg">
          Update
      </button>
  </td>
       <td></td>
      </tr>
      </form>
  </main>
  </div>
    </div>
  </div>
  </div>
    
      </div>
  <br/><!-- Just so that JSFiddle's Result label doesn't overlap the Chart -->

  <div id="update-nav">
    <div id="range-selector">
      <input type="button" id="1m" class="period ui-button" value="1m" />
      <input type="button" id="3m" class="period ui-button" value="3m"/>
      <input type="button" id="6m" class="period ui-button" value="6m"/>
      <input type="button" id="1y" class="period ui-button" value="1y"/>
      <input type="button" id="all" class="period ui-button" value="All"/>
    </div>
    <div id="date-selector" class="">
        From:<input type="text" id="fromDate"  class="ui-widget">
        To:<input type="text" id="toDate"  class="ui-widget">
    </div>
  </div>
  <br/>
  <div id="chartContainer" style="height: 360px; width: 100%;"></div>
</div>
<br>
<script type="text/javascript">

window.onload = function () {
    var dps = [];

var chart = new CanvasJS.Chart("chartContainer",
	{
  title: {
  	text: "Tableau De Bord des heures de travail "
  },
  axisX: {
		title: "Date"
	},
  axisY: {
		title: "Nombre D'heure"
	},
  toolTip:{
		shared: true,
    content: "<strong>Ligne de Crédit: </strong>{Ligne_de_Crédit} </br><strong>Projet: </strong>{Projet} </br> <strong>Date:</strong>{x}</br><strong>Commentaire: </strong>{Commentaire} </br><br> <strong>Nombre D'heures:</strong>{y}</br> "
	},
  data: [
		{
    	type: "bubble",
    	dataPoints: randomData(new Date(2017, 0, 1), 400)
    }
  ]
});
chart.render();

var axisXMin = chart.axisX[0].get("minimum");
var axisXMax = chart.axisX[0].get("maximum");

function randomData(startX, numberOfY){
var xValue, yValue = 0;
@foreach($cra as $cra)
				dps.push({
  
					x: new Date('{{$cra->Date}}'),
          z: {{$cra->nbr_heures}},
					y: {{$cra->nbr_heures}},
          
          Projet: '{{$cra->Projet}}',
             Ligne_de_Crédit:'{{$cra->Ligne_de_Crédit}}',
             Commentaire:'{{$cra->Commentaire}}'
          
         
				});
			@endforeach
      return dps;
}

$( function() {
 	$("#fromDate").val(CanvasJS.formatDate(axisXMin, "DD MMM YYYY"));
  $("#toDate").val(CanvasJS.formatDate(axisXMax, "DD MMM YYYY"));
  $("#fromDate").datepicker({dateFormat: "d M yy"});
  $("#toDate").datepicker({dateFormat: "d M yy"});
});

$("#date-selector").change( function() {
	var minValue = $( "#fromDate" ).val();
  var maxValue = $ ( "#toDate" ).val();
  
  if(new Date(minValue).getTime() < new Date(maxValue).getTime()){  
  	chart.axisX[0].set("minimum", new Date(minValue));
  	chart.axisX[0].set("maximum", new Date(maxValue));
  }  
});

$(".period").click( function() {
	var period = this.id;  
  var minValue;
  minValue = new Date(axisXMax);
  
  switch(period){
  	case "1m":
      minValue.setMonth(minValue.getMonth() - 1);
      break;
    case "3m":
      minValue.setMonth(minValue.getMonth() - 3);
      break;
    case "6m":
      minValue.setMonth(minValue.getMonth() - 6);
      break;
    case "1y":
      minValue.setYear(minValue.getFullYear() - 1);
      break;
    default:
    	minValue = axisXMin;
	}
  
 	chart.axisX[0].set("minimum", new Date(minValue));  
  chart.axisX[0].set("maximum", new Date(axisXMax));
});

}
</script>

@endsection